### ISSUE TITLE
ERROR Couldn't decode JSON (probably HELLO), skipping

### ISSUE THREAD

**Issue by sgraystar** [funtastix/rinnaitouch#95]
Thanks for this integration.

I get this error at each HA restart while there is an active connection to the Rinnai Touch. It has been occurring for several HA releases but does not seem to cause any problem, reporting just in case.

NC-7 controller, no zones, heating only.

Rinnai Touch: 0.12.15
Core 2025.2.5
Supervisor 2025.02.4
Operating System 14.2
Frontend 20250221.0

`2025-03-03 06:51:06.880 DEBUG (SyncWorker_4) [pyrinnaitouch.connection] Client connection created: ('192.168.117.18', 27847)
2025-03-03 06:51:06.881 DEBUG (SyncWorker_4) [pyrinnaitouch.connection] Connected to ('192.168.117.18', 27847)
2025-03-03 06:51:06.882 DEBUG (SyncWorker_4) [pyrinnaitouch.system] Client Connection: <socket.socket fd=40, family=2, type=1, proto=0, laddr=('192.168.117.32', 44960), raddr=('192.168.117.18', 27847)>/False
2025-03-03 06:51:06.886 ERROR (Thread-4 (receiver)) [pyrinnaitouch.receiver] Couldn't decode JSON (probably HELLO), skipping (AttributeError("'NoneType' object has no attribute 'group'"))
2025-03-03 06:51:06.899 INFO (MainThread) [custom_components.rinnaitouch.climate] Set up RinnaiTouch entity 192.168.117.18
2025-03-03 06:51:06.899 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Ext. temp sensor entity name: sensor.rinnai_touch_common_zone_temperature_sensor
2025-03-03 06:51:06.900 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Set up RinnaiTouch zone U entity 192.168.117.18
2025-03-03 06:51:06.900 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Ext temp sensor (U): None
2025-03-03 06:51:07.543 DEBUG (Thread-4 (receiver)) [pyrinnaitouch.receiver] Sequence: 0 Json: [{"SYST": {"CFG": {"MTSP": "N", "NC": "07", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "000", "ZA": "                ", "ZB": "                ", "ZC": "                ", "ZD": "                " }, "AVM": {"HG": "Y", "EC": "N", "CG": "N", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "MON", "TM": "06:52", "BP": "Y", "RG": "Y", "ST": "N", "MD": "H", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "085" } } },{"HGOM": {"CFG": {"ZUIS": "Y", "ZAIS": "N", "ZBIS": "N", "ZCIS": "N", "ZDIS": "N", "CF": "N", "PS": "N", "DG": "A" }, "OOP": {"ST": "F", "CF": "N", "FL": "00", "SN": "N" }, "GSS": {"HC": "N", "FS": "N", "GV": "N", "PH": "N" }, "APS": {"AV": "N" }, "ZUS": {"AE": "N", "MT": "207" }, "ZAS": {"AE": "N", "MT": "207" }, "ZBS": {"AE": "N", "MT": "207" }, "ZCS": {"AE": "N", "MT": "207" }, "ZDS": {"AE": "N", "MT": "207" } } }]
2025-03-03 06:51:07.543 DEBUG (Thread-3 (poll_loop)) [pyrinnaitouch.system_status] We are in HEAT mode
2025-03-03 06:51:07.543 DEBUG (Thread-3 (poll_loop)) [pyrinnaitouch.unit_status] Unit is OFF
2025-03-03 06:51:07.544 DEBUG (Thread-3 (poll_loop)) [custom_components.rinnaitouch.climate] Ext. temp sensor entity name: sensor.rinnai_touch_common_zone_temperature_sensor
2025-03-03 06:51:07.546 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 999
2025-03-03 06:51:07.547 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Internal temperature sensor reports: 999
2025-03-03 06:51:07.550 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Removing entity: rinnaitouch switch.rinnai_touch_cooling_mode_switch
2025-03-03 06:51:07.550 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Removing entity: rinnaitouch switch.rinnai_touch_evap_mode_switch
2025-03-03 06:51:07.550 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Removing entity: rinnaitouch switch.rinnai_touch_water_pump_switch
2025-03-03 06:51:07.551 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Removing entity: rinnaitouch switch.rinnai_touch_evap_fan_switch
2025-03-03 06:51:07.551 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Removing entity: rinnaitouch binary_sensor.rinnai_touch_compressor_active_sensor
2025-03-03 06:51:07.551 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Removing entity: rinnaitouch binary_sensor.rinnai_touch_calling_cool_sensor
2025-03-03 06:51:07.551 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Removing entity: rinnaitouch binary_sensor.rinnai_touch_evap_prewetting_sensor
2025-03-03 06:51:07.552 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Removing entity: rinnaitouch binary_sensor.rinnai_touch_pump_operating_sensor
2025-03-03 06:51:07.552 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Removing entity: rinnaitouch binary_sensor.rinnai_touch_cooler_busy_sensor
2025-03-03 06:51:07.552 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Removing entity: rinnaitouch binary_sensor.rinnai_touch_common_zone_compressor_active_sensor
2025-03-03 06:51:07.553 DEBUG (MainThread) [custom_components.rinnaitouch.climate] Removing entity: rinnaitouch binary_sensor.rinnai_touch_common_zone_calling_cool_sensor`

**Comment by sgraystar** [comment]
I received this additional warning after updating HA Core to 2025.5.1, maybe related.
It is not the first time I have seen it but is does not appear every restart, perhaps only after a core update?

Rinnai Touch: 0.12.15
Core 2025.5.1
Supervisor 2025.04.1
Operating System 15.2
Frontend 20250509.0

`2025-05-11 07:42:07.931 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/pyrinnaitouch/receiver.py:84: SyntaxWarning: invalid escape sequence '\['
  exp = re.search("^.*([0-9]{6}).*(\[[^\[]*\])[^]]*$", str(data))
2025-05-11 07:42:08.100 ERROR (Thread-3 (receiver)) [pyrinnaitouch.receiver] Couldn't decode JSON (probably HELLO), skipping (AttributeError("'NoneType' object has no attribute 'group'"))`
